name: front
description: "A new Flutter project."

# Prevent accidental publishing
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # iOS style icons
  cupertino_icons: ^1.0.8

  # Supabase client for Flutter
  supabase_flutter: ^2.12.0

  # Open URLs in browser
  url_launcher: ^6.3.2

  # Load environment variables from .env
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended Flutter lints
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
